name: release
on:
  push:
    branches: 
      - main
jobs:
   release:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: NPM install
      run: npm ci
    - name: Unit tests
      run: npm test
    - name: End-to-end tests
      run: npm run test:e2e